# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zUiUa-2I8rQpFTmbjyGABczMbNbfZLra

#Zenith
"""

#Quality of food
# libraries
import numpy as np
import matplotlib.pyplot as plt
 
# create a dataset
height = [52, 73, 133, 37, 12]
bars = ('1', '2', '3', '4', '5')
x_pos = np.arange(len(bars))

# Create bars with different colors
plt.bar(x_pos, height, color=['#ac92eb', '#4fc1e8', '#a0d568', '#ffce54', '#ed5564'])

# Create names on the x-axis
plt.xticks(x_pos, bars)
plt.ylabel('Number of Responses')
plt.xlabel('Rating')S
plt.title('Quality of food')
# Show graph
plt.show()

#Food Variety
import matplotlib.pyplot as plt
import numpy as np

x = np.array(["1", "2", "3", "4", "5"])
y = np.array([24, 106, 101, 51, 25])

plt.barh(x, y, color = "#66b3ff")
plt.xlabel('Number of Responses')
plt.ylabel('Rating')
plt.title('Food Variety')
plt.show()

#Adequacy of food and \nposition of queue at the counter
import matplotlib.pyplot as plt

# Setting labels for items in Chart
Rating = ['1', '2', '3', '4', '5']

# Setting size in Chart based on
# given values
Value = [52, 97, 111, 30, 17]

# colors
colors = ['#ffeead', '#96ceb4', '#ff6f69', '#ffcc5c', '#c99789']

# Pie Chart
plt.pie(Value, colors=colors, labels=Rating,
		autopct='%1.1f%%', pctdistance=0.85)

# draw circle
centre_circle = plt.Circle((0, 0), 0.70, fc='white')
fig = plt.gcf()

# Adding Circle in Pie chart
fig.gca().add_artist(centre_circle)

# Adding Title of chart
plt.title('Adequacy of food and \nposition of queue at the counter')

# Displaying Chart
plt.show()

#Hygiene Levels
#Three lines to make our compiler able to draw:
import sys
import matplotlib
matplotlib.use('Agg')

import matplotlib.pyplot as plt
import numpy as np

x1 = np.array([1, 2, 3, 4, 5])
y1 = np.array([82, 59, 106, 58, 2])


plt.plot(x1, y1, c = '#4CAF50')
plt.ylabel('Number of Responses')
plt.xlabel('Rating')
plt.title('Hygiene Levels')
plt.show()

#Overall Rating
import matplotlib.pyplot as plt
import numpy as np

x = np.array(["1", "2", "3", "4", "5"])
y = np.array([50, 86, 110, 40, 21])

plt.bar(x, y, color = ['#ace600', '#d9ff66', '#ffeb66', '#ffcc66', '#ff884d'])
plt.xlabel('Number of Responses')
plt.ylabel('Rating')
plt.title('Overall Rating')
plt.show()

"""#CRCL"""

#Quality of food
# libraries
import numpy as np
import matplotlib.pyplot as plt
 
# create a dataset
height = [43, 57, 140, 54, 10]
bars = ('1', '2', '3', '4', '5')
x_pos = np.arange(len(bars))

# Create bars with different colors
plt.bar(x_pos, height, color=['#ac92eb', '#4fc1e8', '#a0d568', '#ffce54', '#ed5564'])

# Create names on the x-axis
plt.xticks(x_pos, bars)
plt.ylabel('Number of Responses')
plt.xlabel('Rating')
plt.title('Quality of food')
# Show graph
plt.show()

#Food Variety
import matplotlib.pyplot as plt
import numpy as np

x = np.array(["1", "2", "3", "4", "5"])
y = np.array([27, 86, 99, 61, 31])

plt.barh(x, y, color = "#66b3ff")
plt.xlabel('Number of Responses')
plt.ylabel('Rating')
plt.title('Food Variety')
plt.show()

#Adequacy of food and \nposition of queue at the counter
import matplotlib.pyplot as plt

# Setting labels for items in Chart
Rating = ['1', '2', '3', '4', '5']

# Setting size in Chart based on
# given values
Value = [45, 83, 110, 47, 19]

# colors
colors = ['#ffeead', '#96ceb4', '#ff6f69', '#ffcc5c', '#c99789']

# Pie Chart
plt.pie(Value, colors=colors, labels=Rating,
		autopct='%1.1f%%', pctdistance=0.85)

# draw circle
centre_circle = plt.Circle((0, 0), 0.70, fc='white')
fig = plt.gcf()

# Adding Circle in Pie chart
fig.gca().add_artist(centre_circle)

# Adding Title of chart
plt.title('Adequacy of food and \nposition of queue at the counter')

# Displaying Chart
plt.show()

#Hygiene Levels
#Three lines to make our compiler able to draw:
import sys
import matplotlib
matplotlib.use('Agg')

import matplotlib.pyplot as plt
import numpy as np

x1 = np.array([1, 2, 3, 4, 5])
y1 = np.array([60, 67, 110, 56, 11])


plt.plot(x1, y1, c = '#4CAF50')
plt.ylabel('Number of Responses')
plt.xlabel('Rating')
plt.title('Hygiene Levels')
plt.show()

#Overall Rating
import matplotlib.pyplot as plt
import numpy as np

x = np.array(["1", "2", "3", "4", "5"])
y = np.array([35, 45, 120, 77, 27])

plt.bar(x, y, color = ['#ace600', '#d9ff66', '#ffeb66', '#ffcc66', '#ff884d'])
plt.xlabel('Rating')
plt.ylabel('Number Of Responses')
plt.title('Overall Rating')
plt.show()

"""#ABRR"""

#Quality of food
# libraries
import numpy as np
import matplotlib.pyplot as plt
 
# create a dataset
height = [44, 53, 110, 73, 26]
bars = ('1', '2', '3', '4', '5')
x_pos = np.arange(len(bars))

# Create bars with different colors
plt.bar(x_pos, height, color=['#ac92eb', '#4fc1e8', '#a0d568', '#ffce54', '#ed5564'])

# Create names on the x-axis
plt.xticks(x_pos, bars)
plt.ylabel('Number of Responses')
plt.xlabel('Rating')
plt.title('Quality of food')
# Show graph
plt.show()

#Food Variety
import matplotlib.pyplot as plt
import numpy as np

x = np.array(["1", "2", "3", "4", "5"])
y = np.array([20, 51, 104, 70, 61])

plt.barh(x, y, color = "#66b3ff")
plt.xlabel('Number of Responses')
plt.ylabel('Rating')
plt.title('Food Variety')
plt.show()

#Adequacy of food and \nposition of queue at the counter
import matplotlib.pyplot as plt

# Setting labels for items in Chart
Rating = ['1', '2', '3', '4', '5']

# Setting size in Chart based on
# given values
Value = [46, 80, 109, 50, 21]

# colors
colors = ['#ffeead', '#96ceb4', '#ff6f69', '#ffcc5c', '#c99789']

# Pie Chart
plt.pie(Value, colors=colors, labels=Rating, autopct='%1.1f%%', pctdistance=0.85)

# draw circle
centre_circle = plt.Circle((0, 0), 0.70, fc='white')
fig = plt.gcf()

# Adding Circle in Pie chart
fig.gca().add_artist(centre_circle)

# Adding Title of chart
plt.title('Adequacy of food and \nposition of queue at the counter')

# Displaying Chart
plt.show()

#Hygiene Levels
#Three lines to make our compiler able to draw:
import sys
import matplotlib
matplotlib.use('Agg')

import matplotlib.pyplot as plt
import numpy as np

x1 = np.array([1, 2, 3, 4, 5])
y1 = np.array([49, 54, 78, 70, 55])


plt.plot(x1, y1, c = '#4CAF50')
plt.ylabel('Number of Responses')
plt.xlabel('Rating')
plt.title('Hygiene Levels')
plt.show()

#Overall Rating
import matplotlib.pyplot as plt
import numpy as np

x = np.array(["1", "2", "3", "4", "5"])
y = np.array([33, 43, 92, 82, 56])

plt.bar(x, y, color = ['#ace600', '#d9ff66', '#ffeb66', '#ffcc66', '#ff884d'])
plt.xlabel('Number of Responses')
plt.ylabel('Rating')
plt.title('Overall Rating')
plt.show()

"""#Comparison """

#Manipulate 
import matplotlib.pyplot as plt

# Data to plot
labels = 'CRCL', 'ABRR', 'Zenith'
sizes = [370, 210, 270]
colors = ['gold', 'lightcoral', 'lightskyblue']
explode = (0, 0.1, 0)  # explode 1st slice

# Plot
plt.pie(sizes, explode=explode, labels=labels, colors=colors, autopct='%1.1f%%', shadow=True, startangle=140)

plt.axis('equal')
plt.show()